# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[(b'M', 'Male'), (b'F', 'Female')], default=b'M', max_length=1)),
                ('type_of_user', models.CharField(choices=[(b'R', 'Retialer'), (b'C', 'Consumer')], default=b'R', max_length=1)),
                ('is_active', models.CharField(choices=[(b'Y', 'Yes'), (b'N', 'No')], default=b'Y', max_length=1)),
            ],
        ),
    ]
